FROM dddlab/computing:latest

# start binder compatibility
# from https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html

ARG NB_USER
ARG NB_UID
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

COPY . ${HOME}/work
USER root
RUN chown -R ${NB_UID} ${HOME}

USER ${NB_USER}
RUN echo "c.NotebookApp.disable_check_xsrf = True" >> ${HOME}/.jupyter/jupyter_notebook_config.py
